# Generated by Django 3.2 on 2021-05-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210502_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descritption',
            new_name='description',
        ),
    ]
